version: '3'

services:
  wordpress:
    image: wordpress:php7.4-fpm
    container_name: wordpress
    depends_on:
      - mysql
    volumes:
      - ./php-conf/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./core/wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    networks:
      - wordpress-network

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./core/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    cap_add:
      - SYS_NICE
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - '8080:80'
    volumes:
      - ./core/wordpress:/var/www/html
      - ./core/logs/nginx:/var/log/nginx
      - ./nginx-conf:/etc/nginx/conf.d
    restart: always
    networks:
      - wordpress-network

volumes:
  mysql: {}
  wordpress: {}

networks:
  wordpress-network:
    driver: bridge
